// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#include "../ui.h"

lv_obj_t * ui_backlight = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_ButtonBacklightONOFF = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_SliderBacklight = NULL;
lv_obj_t * ui_backlightButtonBack = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_ButtonBacklightONOFF(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_backlightOnOff_clicked(e);
    }
}

void ui_event_SliderBacklight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_backlight_value_changed(e);
    }
}

void ui_event_backlightButtonBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_backlight_screen_init(void)
{
    ui_backlight = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_backlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_backlight, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_backlight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Container1 = lv_obj_create(ui_backlight);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(80));
    lv_obj_set_x(ui_Container1, -1);
    lv_obj_set_y(ui_Container1, -36);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonBacklightONOFF = lv_button_create(ui_Container1);
    lv_obj_set_width(ui_ButtonBacklightONOFF, lv_pct(100));
    lv_obj_set_height(ui_ButtonBacklightONOFF, lv_pct(100));
    lv_obj_set_x(ui_ButtonBacklightONOFF, -13);
    lv_obj_set_y(ui_ButtonBacklightONOFF, -32);
    lv_obj_set_align(ui_ButtonBacklightONOFF, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonBacklightONOFF, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonBacklightONOFF, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBacklightONOFF, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonBacklightONOFF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ButtonBacklightONOFF);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "ON/OFF");

    ui_SliderBacklight = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_SliderBacklight, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBacklight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBacklight, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_height(ui_SliderBacklight, 10);
    lv_obj_set_width(ui_SliderBacklight, lv_pct(80));
    lv_obj_set_align(ui_SliderBacklight, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderBacklight, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderBacklight,
                                                                                                      lv_obj_get_style_pad_right(ui_SliderBacklight, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_backlightButtonBack = lv_button_create(ui_backlight);
    lv_obj_set_width(ui_backlightButtonBack, 100);
    lv_obj_set_height(ui_backlightButtonBack, 50);
    lv_obj_set_align(ui_backlightButtonBack, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_backlightButtonBack, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_backlightButtonBack, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_backlightButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_backlightButtonBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_backlightButtonBack);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "back");

    lv_obj_add_event_cb(ui_ButtonBacklightONOFF, ui_event_ButtonBacklightONOFF, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBacklight, ui_event_SliderBacklight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backlightButtonBack, ui_event_backlightButtonBack, LV_EVENT_ALL, NULL);

}

void ui_backlight_screen_destroy(void)
{
    if(ui_backlight) lv_obj_del(ui_backlight);

    // NULL screen variables
    ui_backlight = NULL;
    ui_Container1 = NULL;
    ui_ButtonBacklightONOFF = NULL;
    ui_Label3 = NULL;
    ui_SliderBacklight = NULL;
    ui_backlightButtonBack = NULL;
    ui_Label4 = NULL;

}
