// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#ifndef UI_BACKLIGHT_H
#define UI_BACKLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_backlight
extern void ui_backlight_screen_init(void);
extern void ui_backlight_screen_destroy(void);
extern lv_obj_t * ui_backlight;
extern lv_obj_t * ui_Container1;
extern void ui_event_ButtonBacklightONOFF(lv_event_t * e);
extern lv_obj_t * ui_ButtonBacklightONOFF;
extern lv_obj_t * ui_Label3;
extern void ui_event_SliderBacklight(lv_event_t * e);
extern lv_obj_t * ui_SliderBacklight;
extern void ui_event_backlightButtonBack(lv_event_t * e);
extern lv_obj_t * ui_backlightButtonBack;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

