// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#include "../ui.h"

lv_obj_t * ui_canClass = NULL;
lv_obj_t * ui_TextArea1Can = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_ButtonCanTest1 = NULL;
lv_obj_t * ui_ButtonCanTest2 = NULL;
lv_obj_t * ui_ButtonCanTest3 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_ButtonCanClassClear = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ButtonCanClassBack = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_ButtonCanTest1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_canTest1_clicked(e);
    }
}

void ui_event_ButtonCanTest2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_canTest2_clicked(e);
    }
}

void ui_event_ButtonCanTest3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_canTest3_clicked(e);
    }
}

void ui_event_ButtonCanClassClear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_CanClassClear_clicked(e);
    }
}

void ui_event_ButtonCanClassBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_canClass_screen_init(void)
{
    ui_canClass = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_canClass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_canClass, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_canClass, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_TextArea1Can = lv_textarea_create(ui_canClass);
    lv_obj_set_width(ui_TextArea1Can, lv_pct(100));
    lv_obj_set_height(ui_TextArea1Can, lv_pct(65));
    lv_obj_set_x(ui_TextArea1Can, -163);
    lv_obj_set_y(ui_TextArea1Can, -136);
    lv_obj_set_align(ui_TextArea1Can, LV_ALIGN_CENTER);

    ui_Container2 = lv_obj_create(ui_canClass);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, lv_pct(15));
    lv_obj_set_x(ui_Container2, 66);
    lv_obj_set_y(ui_Container2, -27);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCanTest1 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_ButtonCanTest1, 100);
    lv_obj_set_height(ui_ButtonCanTest1, 50);
    lv_obj_set_align(ui_ButtonCanTest1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCanTest1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCanTest1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonCanTest2 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_ButtonCanTest2, 100);
    lv_obj_set_height(ui_ButtonCanTest2, 50);
    lv_obj_set_align(ui_ButtonCanTest2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCanTest2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCanTest2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonCanTest3 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_ButtonCanTest3, 100);
    lv_obj_set_height(ui_ButtonCanTest3, 50);
    lv_obj_set_align(ui_ButtonCanTest3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCanTest3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCanTest3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_canClass);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 50);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container3, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCanClassClear = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_ButtonCanClassClear, 100);
    lv_obj_set_height(ui_ButtonCanClassClear, 50);
    lv_obj_set_align(ui_ButtonCanClassClear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCanClassClear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCanClassClear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_ButtonCanClassClear);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "clear");

    ui_ButtonCanClassBack = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_ButtonCanClassBack, 100);
    lv_obj_set_height(ui_ButtonCanClassBack, 50);
    lv_obj_set_align(ui_ButtonCanClassBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCanClassBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCanClassBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ButtonCanClassBack);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "back");

    lv_obj_add_event_cb(ui_ButtonCanTest1, ui_event_ButtonCanTest1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCanTest2, ui_event_ButtonCanTest2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCanTest3, ui_event_ButtonCanTest3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCanClassClear, ui_event_ButtonCanClassClear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCanClassBack, ui_event_ButtonCanClassBack, LV_EVENT_ALL, NULL);

}

void ui_canClass_screen_destroy(void)
{
    if(ui_canClass) lv_obj_del(ui_canClass);

    // NULL screen variables
    ui_canClass = NULL;
    ui_TextArea1Can = NULL;
    ui_Container2 = NULL;
    ui_ButtonCanTest1 = NULL;
    ui_ButtonCanTest2 = NULL;
    ui_ButtonCanTest3 = NULL;
    ui_Container3 = NULL;
    ui_ButtonCanClassClear = NULL;
    ui_Label7 = NULL;
    ui_ButtonCanClassBack = NULL;
    ui_Label6 = NULL;

}
