// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#ifndef UI_CANCLASS_H
#define UI_CANCLASS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_canClass
extern void ui_canClass_screen_init(void);
extern void ui_canClass_screen_destroy(void);
extern lv_obj_t * ui_canClass;
extern lv_obj_t * ui_TextArea1Can;
extern lv_obj_t * ui_Container2;
extern void ui_event_ButtonCanTest1(lv_event_t * e);
extern lv_obj_t * ui_ButtonCanTest1;
extern void ui_event_ButtonCanTest2(lv_event_t * e);
extern lv_obj_t * ui_ButtonCanTest2;
extern void ui_event_ButtonCanTest3(lv_event_t * e);
extern lv_obj_t * ui_ButtonCanTest3;
extern lv_obj_t * ui_Container3;
extern void ui_event_ButtonCanClassClear(lv_event_t * e);
extern lv_obj_t * ui_ButtonCanClassClear;
extern lv_obj_t * ui_Label7;
extern void ui_event_ButtonCanClassBack(lv_event_t * e);
extern lv_obj_t * ui_ButtonCanClassBack;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

