// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#ifndef UI_GPIO_H
#define UI_GPIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GPIO
extern void ui_GPIO_screen_init(void);
extern void ui_GPIO_screen_destroy(void);
extern lv_obj_t * ui_GPIO;
extern lv_obj_t * ui_Screen2Layout1;
extern lv_obj_t * ui_switch0;
extern lv_obj_t * ui_EXTLSIO0;
extern lv_obj_t * ui_LabelIO0;
extern lv_obj_t * ui_switch1;
extern lv_obj_t * ui_EXTLSIO1;
extern lv_obj_t * ui_LabelIO1;
extern lv_obj_t * ui_switch2;
extern lv_obj_t * ui_EXTLSIO2;
extern lv_obj_t * ui_LabelIO2;
extern lv_obj_t * ui_switch3;
extern lv_obj_t * ui_EXTLSIO3;
extern lv_obj_t * ui_LabelIO3;
extern lv_obj_t * ui_switch4;
extern lv_obj_t * ui_EXTLSIO4;
extern lv_obj_t * ui_LabelIO4;
extern lv_obj_t * ui_switch5;
extern lv_obj_t * ui_EXTLSIO5;
extern lv_obj_t * ui_LabelIO5;
extern lv_obj_t * ui_switch6;
extern lv_obj_t * ui_EXTLSIO6;
extern lv_obj_t * ui_LabelIO6;
extern lv_obj_t * ui_switch7;
extern lv_obj_t * ui_EXTLSIO7;
extern lv_obj_t * ui_LabelIO7;
extern lv_obj_t * ui_switch8;
extern lv_obj_t * ui_EXTLSIO8;
extern lv_obj_t * ui_LabelIO8;
extern lv_obj_t * ui_switch9;
extern lv_obj_t * ui_EXTLSIO9;
extern lv_obj_t * ui_LabelIO9;
extern lv_obj_t * ui_switch10;
extern lv_obj_t * ui_EXTLSIO10;
extern lv_obj_t * ui_LabelIO10;
extern lv_obj_t * ui_switch11;
extern lv_obj_t * ui_EXTLSIO11;
extern lv_obj_t * ui_LabelIO11;
extern lv_obj_t * ui_switch12;
extern lv_obj_t * ui_EXTLSIO12;
extern lv_obj_t * ui_LabelIO12;
extern lv_obj_t * ui_switch13;
extern lv_obj_t * ui_EXTLSIO13;
extern lv_obj_t * ui_LabelIO13;
extern lv_obj_t * ui_Screen2Layout2;
extern void ui_event_Src2ButtonBack(lv_event_t * e);
extern lv_obj_t * ui_Src2ButtonBack;
extern lv_obj_t * ui_src2LabelBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

