// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#include "../ui.h"

lv_obj_t * ui_GPIO = NULL;
lv_obj_t * ui_Screen2Layout1 = NULL;
lv_obj_t * ui_switch0 = NULL;
lv_obj_t * ui_EXTLSIO0 = NULL;
lv_obj_t * ui_LabelIO0 = NULL;
lv_obj_t * ui_switch1 = NULL;
lv_obj_t * ui_EXTLSIO1 = NULL;
lv_obj_t * ui_LabelIO1 = NULL;
lv_obj_t * ui_switch2 = NULL;
lv_obj_t * ui_EXTLSIO2 = NULL;
lv_obj_t * ui_LabelIO2 = NULL;
lv_obj_t * ui_switch3 = NULL;
lv_obj_t * ui_EXTLSIO3 = NULL;
lv_obj_t * ui_LabelIO3 = NULL;
lv_obj_t * ui_switch4 = NULL;
lv_obj_t * ui_EXTLSIO4 = NULL;
lv_obj_t * ui_LabelIO4 = NULL;
lv_obj_t * ui_switch5 = NULL;
lv_obj_t * ui_EXTLSIO5 = NULL;
lv_obj_t * ui_LabelIO5 = NULL;
lv_obj_t * ui_switch6 = NULL;
lv_obj_t * ui_EXTLSIO6 = NULL;
lv_obj_t * ui_LabelIO6 = NULL;
lv_obj_t * ui_switch7 = NULL;
lv_obj_t * ui_EXTLSIO7 = NULL;
lv_obj_t * ui_LabelIO7 = NULL;
lv_obj_t * ui_switch8 = NULL;
lv_obj_t * ui_EXTLSIO8 = NULL;
lv_obj_t * ui_LabelIO8 = NULL;
lv_obj_t * ui_switch9 = NULL;
lv_obj_t * ui_EXTLSIO9 = NULL;
lv_obj_t * ui_LabelIO9 = NULL;
lv_obj_t * ui_switch10 = NULL;
lv_obj_t * ui_EXTLSIO10 = NULL;
lv_obj_t * ui_LabelIO10 = NULL;
lv_obj_t * ui_switch11 = NULL;
lv_obj_t * ui_EXTLSIO11 = NULL;
lv_obj_t * ui_LabelIO11 = NULL;
lv_obj_t * ui_switch12 = NULL;
lv_obj_t * ui_EXTLSIO12 = NULL;
lv_obj_t * ui_LabelIO12 = NULL;
lv_obj_t * ui_switch13 = NULL;
lv_obj_t * ui_EXTLSIO13 = NULL;
lv_obj_t * ui_LabelIO13 = NULL;
lv_obj_t * ui_Screen2Layout2 = NULL;
lv_obj_t * ui_Src2ButtonBack = NULL;
lv_obj_t * ui_src2LabelBack = NULL;
// event funtions
void ui_event_Src2ButtonBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_OUT, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_GPIO_screen_init(void)
{
    ui_GPIO = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_GPIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_GPIO, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_GPIO, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Screen2Layout1 = lv_obj_create(ui_GPIO);
    lv_obj_remove_style_all(ui_Screen2Layout1);
    lv_obj_set_width(ui_Screen2Layout1, lv_pct(100));
    lv_obj_set_height(ui_Screen2Layout1, lv_pct(75));
    lv_obj_set_x(ui_Screen2Layout1, 297);
    lv_obj_set_y(ui_Screen2Layout1, 191);
    lv_obj_set_align(ui_Screen2Layout1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen2Layout1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Screen2Layout1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen2Layout1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Screen2Layout1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen2Layout1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2Layout1, &ui_font_tw1616, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch0 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch0);
    lv_obj_set_height(ui_switch0, 50);
    lv_obj_set_width(ui_switch0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch0, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch0, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch0, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO0 = lv_switch_create(ui_switch0);
    lv_obj_set_width(ui_EXTLSIO0, 50);
    lv_obj_set_height(ui_EXTLSIO0, 25);
    lv_obj_set_align(ui_EXTLSIO0, LV_ALIGN_CENTER);

    ui_LabelIO0 = lv_label_create(ui_switch0);
    lv_obj_set_width(ui_LabelIO0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO0, "EXT_LS_IO0");

    ui_switch1 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch1);
    lv_obj_set_height(ui_switch1, 50);
    lv_obj_set_width(ui_switch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO1 = lv_switch_create(ui_switch1);
    lv_obj_set_width(ui_EXTLSIO1, 50);
    lv_obj_set_height(ui_EXTLSIO1, 25);
    lv_obj_set_align(ui_EXTLSIO1, LV_ALIGN_CENTER);

    ui_LabelIO1 = lv_label_create(ui_switch1);
    lv_obj_set_width(ui_LabelIO1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO1, "EXT_LS_IO1");

    ui_switch2 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch2);
    lv_obj_set_height(ui_switch2, 50);
    lv_obj_set_width(ui_switch2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO2 = lv_switch_create(ui_switch2);
    lv_obj_set_width(ui_EXTLSIO2, 50);
    lv_obj_set_height(ui_EXTLSIO2, 25);
    lv_obj_set_align(ui_EXTLSIO2, LV_ALIGN_CENTER);

    ui_LabelIO2 = lv_label_create(ui_switch2);
    lv_obj_set_width(ui_LabelIO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO2, "EXT_LS_IO2");

    ui_switch3 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch3);
    lv_obj_set_height(ui_switch3, 50);
    lv_obj_set_width(ui_switch3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO3 = lv_switch_create(ui_switch3);
    lv_obj_set_width(ui_EXTLSIO3, 50);
    lv_obj_set_height(ui_EXTLSIO3, 25);
    lv_obj_set_align(ui_EXTLSIO3, LV_ALIGN_CENTER);

    ui_LabelIO3 = lv_label_create(ui_switch3);
    lv_obj_set_width(ui_LabelIO3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO3, "EXT_LS_IO3");

    ui_switch4 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch4);
    lv_obj_set_height(ui_switch4, 50);
    lv_obj_set_width(ui_switch4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO4 = lv_switch_create(ui_switch4);
    lv_obj_set_width(ui_EXTLSIO4, 50);
    lv_obj_set_height(ui_EXTLSIO4, 25);
    lv_obj_set_align(ui_EXTLSIO4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EXTLSIO4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EXTLSIO4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_LabelIO4 = lv_label_create(ui_switch4);
    lv_obj_set_width(ui_LabelIO4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO4, "EXT_LS_IO4");

    ui_switch5 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch5);
    lv_obj_set_height(ui_switch5, 50);
    lv_obj_set_width(ui_switch5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO5 = lv_switch_create(ui_switch5);
    lv_obj_set_width(ui_EXTLSIO5, 50);
    lv_obj_set_height(ui_EXTLSIO5, 25);
    lv_obj_set_align(ui_EXTLSIO5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EXTLSIO5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_EXTLSIO5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_LabelIO5 = lv_label_create(ui_switch5);
    lv_obj_set_width(ui_LabelIO5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO5, "EXT_LS_IO5");

    ui_switch6 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch6);
    lv_obj_set_height(ui_switch6, 50);
    lv_obj_set_width(ui_switch6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO6 = lv_switch_create(ui_switch6);
    lv_obj_set_width(ui_EXTLSIO6, 50);
    lv_obj_set_height(ui_EXTLSIO6, 25);
    lv_obj_set_align(ui_EXTLSIO6, LV_ALIGN_CENTER);

    ui_LabelIO6 = lv_label_create(ui_switch6);
    lv_obj_set_width(ui_LabelIO6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO6, "EXT_LS_IO6");

    ui_switch7 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch7);
    lv_obj_set_height(ui_switch7, 50);
    lv_obj_set_width(ui_switch7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO7 = lv_switch_create(ui_switch7);
    lv_obj_set_width(ui_EXTLSIO7, 50);
    lv_obj_set_height(ui_EXTLSIO7, 25);
    lv_obj_set_align(ui_EXTLSIO7, LV_ALIGN_CENTER);

    ui_LabelIO7 = lv_label_create(ui_switch7);
    lv_obj_set_width(ui_LabelIO7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO7, "EXT_LS_IO7");

    ui_switch8 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch8);
    lv_obj_set_height(ui_switch8, 50);
    lv_obj_set_width(ui_switch8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO8 = lv_switch_create(ui_switch8);
    lv_obj_set_width(ui_EXTLSIO8, 50);
    lv_obj_set_height(ui_EXTLSIO8, 25);
    lv_obj_set_align(ui_EXTLSIO8, LV_ALIGN_CENTER);

    ui_LabelIO8 = lv_label_create(ui_switch8);
    lv_obj_set_width(ui_LabelIO8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO8, "EXT_LS_IO8");

    ui_switch9 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch9);
    lv_obj_set_height(ui_switch9, 50);
    lv_obj_set_width(ui_switch9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO9 = lv_switch_create(ui_switch9);
    lv_obj_set_width(ui_EXTLSIO9, 50);
    lv_obj_set_height(ui_EXTLSIO9, 25);
    lv_obj_set_align(ui_EXTLSIO9, LV_ALIGN_CENTER);

    ui_LabelIO9 = lv_label_create(ui_switch9);
    lv_obj_set_width(ui_LabelIO9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO9, "EXT_LS_IO9");

    ui_switch10 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch10);
    lv_obj_set_height(ui_switch10, 50);
    lv_obj_set_width(ui_switch10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO10 = lv_switch_create(ui_switch10);
    lv_obj_set_width(ui_EXTLSIO10, 50);
    lv_obj_set_height(ui_EXTLSIO10, 25);
    lv_obj_set_align(ui_EXTLSIO10, LV_ALIGN_CENTER);

    ui_LabelIO10 = lv_label_create(ui_switch10);
    lv_obj_set_width(ui_LabelIO10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO10, "EXT_LS_IO10");

    ui_switch11 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch11);
    lv_obj_set_height(ui_switch11, 50);
    lv_obj_set_width(ui_switch11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch11, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO11 = lv_switch_create(ui_switch11);
    lv_obj_set_width(ui_EXTLSIO11, 50);
    lv_obj_set_height(ui_EXTLSIO11, 25);
    lv_obj_set_align(ui_EXTLSIO11, LV_ALIGN_CENTER);

    ui_LabelIO11 = lv_label_create(ui_switch11);
    lv_obj_set_width(ui_LabelIO11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO11, "EXT_LS_IO11");

    ui_switch12 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch12);
    lv_obj_set_height(ui_switch12, 50);
    lv_obj_set_width(ui_switch12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch12, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO12 = lv_switch_create(ui_switch12);
    lv_obj_set_width(ui_EXTLSIO12, 50);
    lv_obj_set_height(ui_EXTLSIO12, 25);
    lv_obj_set_align(ui_EXTLSIO12, LV_ALIGN_CENTER);

    ui_LabelIO12 = lv_label_create(ui_switch12);
    lv_obj_set_width(ui_LabelIO12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO12, "EXT_ESP_IO0");

    ui_switch13 = lv_obj_create(ui_Screen2Layout1);
    lv_obj_remove_style_all(ui_switch13);
    lv_obj_set_height(ui_switch13, 50);
    lv_obj_set_width(ui_switch13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_switch13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_switch13, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_switch13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EXTLSIO13 = lv_switch_create(ui_switch13);
    lv_obj_set_width(ui_EXTLSIO13, 50);
    lv_obj_set_height(ui_EXTLSIO13, 25);
    lv_obj_set_align(ui_EXTLSIO13, LV_ALIGN_CENTER);

    ui_LabelIO13 = lv_label_create(ui_switch13);
    lv_obj_set_width(ui_LabelIO13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIO13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIO13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIO13, "EXT_ESP_IO1");

    ui_Screen2Layout2 = lv_obj_create(ui_GPIO);
    lv_obj_remove_style_all(ui_Screen2Layout2);
    lv_obj_set_width(ui_Screen2Layout2, lv_pct(100));
    lv_obj_set_height(ui_Screen2Layout2, lv_pct(20));
    lv_obj_set_x(ui_Screen2Layout2, -299);
    lv_obj_set_y(ui_Screen2Layout2, -219);
    lv_obj_set_align(ui_Screen2Layout2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen2Layout2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Src2ButtonBack = lv_button_create(ui_Screen2Layout2);
    lv_obj_set_width(ui_Src2ButtonBack, 100);
    lv_obj_set_height(ui_Src2ButtonBack, 50);
    lv_obj_set_align(ui_Src2ButtonBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Src2ButtonBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Src2ButtonBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_src2LabelBack = lv_label_create(ui_Src2ButtonBack);
    lv_obj_set_width(ui_src2LabelBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_src2LabelBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_src2LabelBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_src2LabelBack, "back");

    lv_obj_add_event_cb(ui_Src2ButtonBack, ui_event_Src2ButtonBack, LV_EVENT_ALL, NULL);

}

void ui_GPIO_screen_destroy(void)
{
    if(ui_GPIO) lv_obj_del(ui_GPIO);

    // NULL screen variables
    ui_GPIO = NULL;
    ui_Screen2Layout1 = NULL;
    ui_switch0 = NULL;
    ui_EXTLSIO0 = NULL;
    ui_LabelIO0 = NULL;
    ui_switch1 = NULL;
    ui_EXTLSIO1 = NULL;
    ui_LabelIO1 = NULL;
    ui_switch2 = NULL;
    ui_EXTLSIO2 = NULL;
    ui_LabelIO2 = NULL;
    ui_switch3 = NULL;
    ui_EXTLSIO3 = NULL;
    ui_LabelIO3 = NULL;
    ui_switch4 = NULL;
    ui_EXTLSIO4 = NULL;
    ui_LabelIO4 = NULL;
    ui_switch5 = NULL;
    ui_EXTLSIO5 = NULL;
    ui_LabelIO5 = NULL;
    ui_switch6 = NULL;
    ui_EXTLSIO6 = NULL;
    ui_LabelIO6 = NULL;
    ui_switch7 = NULL;
    ui_EXTLSIO7 = NULL;
    ui_LabelIO7 = NULL;
    ui_switch8 = NULL;
    ui_EXTLSIO8 = NULL;
    ui_LabelIO8 = NULL;
    ui_switch9 = NULL;
    ui_EXTLSIO9 = NULL;
    ui_LabelIO9 = NULL;
    ui_switch10 = NULL;
    ui_EXTLSIO10 = NULL;
    ui_LabelIO10 = NULL;
    ui_switch11 = NULL;
    ui_EXTLSIO11 = NULL;
    ui_LabelIO11 = NULL;
    ui_switch12 = NULL;
    ui_EXTLSIO12 = NULL;
    ui_LabelIO12 = NULL;
    ui_switch13 = NULL;
    ui_EXTLSIO13 = NULL;
    ui_LabelIO13 = NULL;
    ui_Screen2Layout2 = NULL;
    ui_Src2ButtonBack = NULL;
    ui_src2LabelBack = NULL;

}
