// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#include "../ui.h"

lv_obj_t * ui_imgView = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions

// build funtions

void ui_imgView_screen_init(void)
{
    ui_imgView = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_imgView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_imgView);
    lv_image_set_src(ui_Image1, &ui_img_689278962);
    lv_obj_set_width(ui_Image1, lv_pct(100));
    lv_obj_set_height(ui_Image1, lv_pct(100));
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image1, 900);
    lv_image_set_scale(ui_Image1, 512);

}

void ui_imgView_screen_destroy(void)
{
    if(ui_imgView) lv_obj_del(ui_imgView);

    // NULL screen variables
    ui_imgView = NULL;
    ui_Image1 = NULL;

}
