// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#ifndef UI_IMGVIEW_H
#define UI_IMGVIEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_imgView
extern void ui_imgView_screen_init(void);
extern void ui_imgView_screen_destroy(void);
extern lv_obj_t * ui_imgView;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

