// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Screen1Row1 = NULL;
lv_obj_t * ui_Screen1Row2 = NULL;
lv_obj_t * ui_ButtonGPIO = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ButtonBacklight = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ButtonCanClass = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Screen1Row3 = NULL;
// event funtions
void ui_event_ButtonGPIO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GPIO, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_GPIO_screen_init);
    }
}

void ui_event_ButtonBacklight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_Backlight_clicked(e);
    }
}

void ui_event_ButtonCanClass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_CanClass_clicked(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Screen1Row1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Screen1Row1);
    lv_obj_set_width(ui_Screen1Row1, lv_pct(100));
    lv_obj_set_flex_grow(ui_Screen1Row1, 1);
    lv_obj_set_x(ui_Screen1Row1, -163);
    lv_obj_set_y(ui_Screen1Row1, -23);
    lv_obj_set_align(ui_Screen1Row1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1Row1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1Row1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Screen1Row1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Row2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Screen1Row2);
    lv_obj_set_width(ui_Screen1Row2, lv_pct(100));
    lv_obj_set_flex_grow(ui_Screen1Row2, 1);
    lv_obj_set_x(ui_Screen1Row2, -133);
    lv_obj_set_y(ui_Screen1Row2, 71);
    lv_obj_set_align(ui_Screen1Row2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1Row2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Screen1Row2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Screen1Row2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Screen1Row2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Screen1Row2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGPIO = lv_button_create(ui_Screen1Row2);
    lv_obj_set_width(ui_ButtonGPIO, 100);
    lv_obj_set_height(ui_ButtonGPIO, 50);
    lv_obj_set_x(ui_ButtonGPIO, -181);
    lv_obj_set_y(ui_ButtonGPIO, 13);
    lv_obj_set_align(ui_ButtonGPIO, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonGPIO, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ButtonGPIO, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGPIO, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonGPIO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ButtonGPIO);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "GPIO");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_tw1616, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonBacklight = lv_button_create(ui_Screen1Row2);
    lv_obj_set_width(ui_ButtonBacklight, 100);
    lv_obj_set_height(ui_ButtonBacklight, 50);
    lv_obj_set_x(ui_ButtonBacklight, -23);
    lv_obj_set_y(ui_ButtonBacklight, 119);
    lv_obj_set_align(ui_ButtonBacklight, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ButtonBacklight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ButtonBacklight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonBacklight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonBacklight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ButtonBacklight);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "backlight");

    ui_ButtonCanClass = lv_button_create(ui_Screen1Row2);
    lv_obj_set_width(ui_ButtonCanClass, 100);
    lv_obj_set_height(ui_ButtonCanClass, 50);
    lv_obj_set_align(ui_ButtonCanClass, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCanClass, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCanClass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_ButtonCanClass);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "can class");

    ui_Screen1Row3 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Screen1Row3);
    lv_obj_set_width(ui_Screen1Row3, lv_pct(100));
    lv_obj_set_flex_grow(ui_Screen1Row3, 1);
    lv_obj_set_x(ui_Screen1Row3, 30);
    lv_obj_set_y(ui_Screen1Row3, 156);
    lv_obj_set_align(ui_Screen1Row3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Screen1Row3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1Row3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Screen1Row3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonGPIO, ui_event_ButtonGPIO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBacklight, ui_event_ButtonBacklight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCanClass, ui_event_ButtonCanClass, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Screen1Row1 = NULL;
    ui_Screen1Row2 = NULL;
    ui_ButtonGPIO = NULL;
    ui_Label1 = NULL;
    ui_ButtonBacklight = NULL;
    ui_Label2 = NULL;
    ui_ButtonCanClass = NULL;
    ui_Label5 = NULL;
    ui_Screen1Row3 = NULL;

}
