// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1Row1;
extern lv_obj_t * ui_Screen1Row2;
extern void ui_event_ButtonGPIO(lv_event_t * e);
extern lv_obj_t * ui_ButtonGPIO;
extern lv_obj_t * ui_Label1;
extern void ui_event_ButtonBacklight(lv_event_t * e);
extern lv_obj_t * ui_ButtonBacklight;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Screen1Row3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

