// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#ifndef UI_UART0_H
#define UI_UART0_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uart0
extern void ui_uart0_screen_init(void);
extern void ui_uart0_screen_destroy(void);
extern lv_obj_t * ui_uart0;
extern lv_obj_t * ui_TextArea1Uart0;
extern lv_obj_t * ui_Container6;
extern void ui_event_ButtonUart0Send1(lv_event_t * e);
extern lv_obj_t * ui_ButtonUart0Send1;
extern void ui_event_ButtonUart0Send2(lv_event_t * e);
extern lv_obj_t * ui_ButtonUart0Send2;
extern void ui_event_ButtonUart0Send3(lv_event_t * e);
extern lv_obj_t * ui_ButtonUart0Send3;
extern lv_obj_t * ui_Container7;
extern void ui_event_ButtonUart0Clear(lv_event_t * e);
extern lv_obj_t * ui_ButtonUart0Clear;
extern void ui_event_ButtonUart0Back(lv_event_t * e);
extern lv_obj_t * ui_ButtonUart0Back;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

