// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#include "../ui.h"

lv_obj_t * ui_uart0 = NULL;
lv_obj_t * ui_TextArea1Uart0 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_ButtonUart0Send1 = NULL;
lv_obj_t * ui_ButtonUart0Send2 = NULL;
lv_obj_t * ui_ButtonUart0Send3 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_ButtonUart0Clear = NULL;
lv_obj_t * ui_ButtonUart0Back = NULL;
// event funtions
void ui_event_ButtonUart0Send1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_uart0Test1_clicked(e);
    }
}

void ui_event_ButtonUart0Send2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_uart0Test2_clicked(e);
    }
}

void ui_event_ButtonUart0Send3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Button_uart0Test3_clicked(e);
    }
}

void ui_event_ButtonUart0Clear(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_uart0Clear_clicked(e);
    }
}

void ui_event_ButtonUart0Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_uart0_screen_init(void)
{
    ui_uart0 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_uart0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_uart0, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_uart0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_TextArea1Uart0 = lv_textarea_create(ui_uart0);
    lv_obj_set_width(ui_TextArea1Uart0, lv_pct(100));
    lv_obj_set_height(ui_TextArea1Uart0, lv_pct(65));
    lv_obj_set_x(ui_TextArea1Uart0, 0);
    lv_obj_set_y(ui_TextArea1Uart0, 28);
    lv_obj_set_align(ui_TextArea1Uart0, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1Uart0, "Only displays in HEX format");

    ui_Container6 = lv_obj_create(ui_uart0);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(15));
    lv_obj_set_x(ui_Container6, -29);
    lv_obj_set_y(ui_Container6, 176);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container6, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonUart0Send1 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_ButtonUart0Send1, 100);
    lv_obj_set_height(ui_ButtonUart0Send1, 50);
    lv_obj_set_x(ui_ButtonUart0Send1, -218);
    lv_obj_set_y(ui_ButtonUart0Send1, 78);
    lv_obj_set_align(ui_ButtonUart0Send1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUart0Send1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonUart0Send1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonUart0Send2 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_ButtonUart0Send2, 100);
    lv_obj_set_height(ui_ButtonUart0Send2, 50);
    lv_obj_set_align(ui_ButtonUart0Send2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUart0Send2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonUart0Send2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonUart0Send3 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_ButtonUart0Send3, 100);
    lv_obj_set_height(ui_ButtonUart0Send3, 50);
    lv_obj_set_align(ui_ButtonUart0Send3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUart0Send3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonUart0Send3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_uart0);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 50);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_x(ui_Container7, -41);
    lv_obj_set_y(ui_Container7, 201);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container7, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonUart0Clear = lv_button_create(ui_Container7);
    lv_obj_set_width(ui_ButtonUart0Clear, 100);
    lv_obj_set_height(ui_ButtonUart0Clear, 50);
    lv_obj_set_align(ui_ButtonUart0Clear, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUart0Clear, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonUart0Clear, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonUart0Back = lv_button_create(ui_Container7);
    lv_obj_set_width(ui_ButtonUart0Back, 100);
    lv_obj_set_height(ui_ButtonUart0Back, 50);
    lv_obj_set_align(ui_ButtonUart0Back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUart0Back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonUart0Back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonUart0Send1, ui_event_ButtonUart0Send1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUart0Send2, ui_event_ButtonUart0Send2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUart0Send3, ui_event_ButtonUart0Send3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUart0Clear, ui_event_ButtonUart0Clear, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUart0Back, ui_event_ButtonUart0Back, LV_EVENT_ALL, NULL);

}

void ui_uart0_screen_destroy(void)
{
    if(ui_uart0) lv_obj_del(ui_uart0);

    // NULL screen variables
    ui_uart0 = NULL;
    ui_TextArea1Uart0 = NULL;
    ui_Container6 = NULL;
    ui_ButtonUart0Send1 = NULL;
    ui_ButtonUart0Send2 = NULL;
    ui_ButtonUart0Send3 = NULL;
    ui_Container7 = NULL;
    ui_ButtonUart0Clear = NULL;
    ui_ButtonUart0Back = NULL;

}
