/* for SquareLine Studio
   To avoid overwriting existing functions when updating the UI generated by SquareLine Studio,
   the required functions are placed in this file.
   Note: The function names must match the event names generated in the SquareLine Studio UI.*/

#include "lvgl.h"
#include "lcd_backlight/lcd_backlight.h"
#include "aw9523.h"
#include "ui.h"

//********* page:Screen1 *********
void Button_Backlight_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        #if BACKLIGHT_PWM_ENABLE
        lv_obj_add_flag(ui_ButtonBacklightONOFF, LV_OBJ_FLAG_HIDDEN);
        #else
        lv_obj_add_flag(ui_SliderBacklight, LV_OBJ_FLAG_HIDDEN);
        #endif

        _ui_screen_change(&ui_backlight, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_backlight_screen_init);
    }
}
//********* page:Screen1 end *********

//********* page:GPIO *********
void switch_IO__value_changed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * switch_obj = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        if(switch_obj == ui_EXTLSIO0)
        {
            aw9523_io_set_level(AW9523_PORT_0, 0, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO1)
        {
            aw9523_io_set_level(AW9523_PORT_0, 1, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO2)  
        {
            aw9523_io_set_level(AW9523_PORT_0, 2, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO3)
        {
            aw9523_io_set_level(AW9523_PORT_0, 3, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO4)
        {
            aw9523_io_set_level(AW9523_PORT_0, 4, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO5)
        {
            aw9523_io_set_level(AW9523_PORT_0, 5, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO6)
        {
            aw9523_io_set_level(AW9523_PORT_0, 6, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO7)
        {
            aw9523_io_set_level(AW9523_PORT_0, 7, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO8)
        {
            aw9523_io_set_level(AW9523_PORT_1, 4, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO9)
        {
            aw9523_io_set_level(AW9523_PORT_1, 5, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO10)
        {
            aw9523_io_set_level(AW9523_PORT_1, 6, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO11)
        {
            aw9523_io_set_level(AW9523_PORT_1, 7, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
    }
}
//********* page:GPIO end *********

//********* page:imgView *********
//********* page:imgView end *********

//********* page:backlight *********
void button_backlightOnOff_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    static uint8_t backlight_status = 1;

    if(event_code == LV_EVENT_CLICKED) {
        lcd_backlight_onoff(!backlight_status);
        backlight_status = !backlight_status;
    }
}

void slider_backlight_value_changed(lv_event_t * e)
{
    #if BACKLIGHT_PWM_ENABLE
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * slider = lv_event_get_target_obj(e);
    
        if(event_code == LV_EVENT_VALUE_CHANGED) {
            lcd_backlight_set_pwm_duty(lv_slider_get_value(slider));
        }
    #endif
}
//********* page:backlight end *********