/* for SquareLine Studio
   To avoid overwriting existing functions when updating the UI generated by SquareLine Studio,
   the required functions are placed in this file.
   Note: The function names must match the event names generated in the SquareLine Studio UI.*/

#include "lvgl.h"
#include "esp_lvgl_port.h"
#include "lcd_backlight/lcd_backlight.h"
#include "aw9523.h"
#include "ui.h"
#include "esp_log.h"
#include "twai/BSP_TWAI.h"

#define TAG "SquareLine_cb"

TaskHandle_t TextArea1Can_taskHandle = NULL;
static char TextArea1Can_insertText[128] ={0};
void TextArea1Can_task(void *arg);

//********* page:Screen1 *********
void Button_Backlight_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) 
    {
        #if BACKLIGHT_PWM_ENABLE
        lv_obj_add_flag(ui_ButtonBacklightONOFF, LV_OBJ_FLAG_HIDDEN);
        #else
        lv_obj_add_flag(ui_SliderBacklight, LV_OBJ_FLAG_HIDDEN);
        #endif

        _ui_screen_change(&ui_backlight, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_backlight_screen_init);
    }
}

void Button_CanClass_clicked(lv_event_t * e)
{
    if(!TextArea1Can_taskHandle)// first time to click the button, create a task to receive the CAN message and add some labels to the button
    {
        xTaskCreate(TextArea1Can_task, "TextArea1Can_task", 4096, NULL, 10, &TextArea1Can_taskHandle);// create a task to receive the CAN message

        lv_obj_t* Label_canTest1 = lv_label_create(ui_ButtonCanTest1);
        lv_obj_set_width(Label_canTest1, LV_SIZE_CONTENT);   
        lv_obj_set_height(Label_canTest1, LV_SIZE_CONTENT);    
        lv_obj_set_align(Label_canTest1, LV_ALIGN_CENTER);
        lv_label_set_text(Label_canTest1, "send test 1");

        lv_obj_t* Label_canTest2 = lv_label_create(ui_ButtonCanTest2);
        lv_obj_set_width(Label_canTest2, LV_SIZE_CONTENT);   
        lv_obj_set_height(Label_canTest2, LV_SIZE_CONTENT);    
        lv_obj_set_align(Label_canTest2, LV_ALIGN_CENTER);
        lv_label_set_text(Label_canTest2, "can test 2");

        lv_obj_t* Label_canTest3 = lv_label_create(ui_ButtonCanTest3);
        lv_obj_set_width(Label_canTest3, LV_SIZE_CONTENT);   
        lv_obj_set_height(Label_canTest3, LV_SIZE_CONTENT);    
        lv_obj_set_align(Label_canTest3, LV_ALIGN_CENTER);
        lv_label_set_text(Label_canTest3, "can test 3");
    }
    
    _ui_screen_change(&ui_canClass, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_canClass_screen_init);
}

void Button_imgView_clicked(lv_event_t * e)
{
    // Set the opacity of the button to 0 when it is pressed
    static const lv_style_prop_t props[] = {LV_STYLE_OPA, 0}; // Listen for opacity property

    static lv_style_transition_dsc_t trans_def;
    lv_style_transition_dsc_init(&trans_def, props, lv_anim_path_linear, 200, 0, NULL); 

    static lv_style_transition_dsc_t trans_pr;
    lv_style_transition_dsc_init(&trans_pr, props, lv_anim_path_linear, 200, 0, NULL);

    static lv_style_t style_def;// Default style
    lv_style_init(&style_def);
    lv_style_set_opa(&style_def, LV_OPA_0); // Initial opacity 0%      
    lv_style_set_transition(&style_def, &trans_def);

    static lv_style_t style_pr;
    lv_style_init(&style_pr);
    lv_style_set_opa(&style_pr, LV_OPA_100); // Opacity 100% after pressed
    lv_style_set_bg_color(&style_pr, lv_palette_main(LV_PALETTE_GREY));
    lv_style_set_transition(&style_pr, &trans_pr);    

    lv_obj_add_style(ui_imgViewButtonLeft, &style_def, 0);               
    lv_obj_add_style(ui_imgViewButtonLeft, &style_pr, LV_STATE_PRESSED); 
    lv_obj_add_style(ui_imgViewButtonRight, &style_def, 0);               
    lv_obj_add_style(ui_imgViewButtonRight, &style_pr, LV_STATE_PRESSED); 

    _ui_screen_change(&ui_imgView, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_imgView_screen_init);
}
//********* page:Screen1 end *********

//********* page:GPIO *********
void switch_IO__value_changed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * switch_obj = lv_event_get_target_obj(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        if(switch_obj == ui_EXTLSIO0)
        {
            aw9523_io_set_level(AW9523_PORT_0, 0, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO1)
        {
            aw9523_io_set_level(AW9523_PORT_0, 1, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO2)  
        {
            aw9523_io_set_level(AW9523_PORT_0, 2, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO3)
        {
            aw9523_io_set_level(AW9523_PORT_0, 3, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO4)
        {
            aw9523_io_set_level(AW9523_PORT_0, 4, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO5)
        {
            aw9523_io_set_level(AW9523_PORT_0, 5, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO6)
        {
            aw9523_io_set_level(AW9523_PORT_0, 6, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO7)
        {
            aw9523_io_set_level(AW9523_PORT_0, 7, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO8)
        {
            aw9523_io_set_level(AW9523_PORT_1, 4, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO9)
        {
            aw9523_io_set_level(AW9523_PORT_1, 5, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO10)
        {
            aw9523_io_set_level(AW9523_PORT_1, 6, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
        else if(switch_obj == ui_EXTLSIO11)
        {
            aw9523_io_set_level(AW9523_PORT_1, 7, lv_obj_has_state(switch_obj, LV_STATE_CHECKED));
        }
    }
}
//********* page:GPIO end *********

//********* page:backlight *********
void button_backlightOnOff_clicked(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    static uint8_t backlight_status = 1;

    if(event_code == LV_EVENT_CLICKED) {
        lcd_backlight_onoff(!backlight_status);
        backlight_status = !backlight_status;
    }
}

void slider_backlight_value_changed(lv_event_t * e)
{
    #if BACKLIGHT_PWM_ENABLE
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * slider = lv_event_get_target_obj(e);
    
        if(event_code == LV_EVENT_VALUE_CHANGED) {
            lcd_backlight_set_pwm_duty(lv_slider_get_value(slider));
        }
    #endif
}
//********* page:backlight end *********

//********* page:canClass *********
void TextArea1Can_update_text_cb(void * user_data) 
{
    lv_textarea_add_text(ui_TextArea1Can, user_data);     
}

void TextArea1Can_task(void *arg) 
{
    ESP_LOGI(TAG, "TextArea1Can_task started");

    while(1)
    {
        twai_message_t message;
        QueueHandle_t* twai_RX_message_queue = twai_get_rx_queue();
        if(xQueueReceive(*twai_RX_message_queue, &message, pdMS_TO_TICKS(100)) == pdPASS)
        {                   
            // For thread safety, update the UI asynchronously in the LVGL thread
            TextArea1Can_insertText[0] = '\0';
            snprintf(TextArea1Can_insertText, sizeof(TextArea1Can_insertText), "Message received: %s ID=0x%03lX, Data=[%02X %02X %02X %02X %02X %02X %02X %02X]\r\n",
                    message.extd ? "Extended" : "Standard",
                    message.identifier,
                    message.data[0], message.data[1], message.data[2], message.data[3],
                    message.data[4], message.data[5], message.data[6], message.data[7]);

            lv_async_call(TextArea1Can_update_text_cb, &TextArea1Can_insertText); // For thread safety, needs to be called asynchronously and executed in the LVGL thread
        }
    }
}

void Button_canTest1_clicked(lv_event_t * e)
{
    // ESP_LOGI(TAG,"Button_canTest1_clicked\n");
    twai_message_t message;
    message.identifier = 0x000;
    message.data_length_code = 8;
    message.data[0] = 0x0A;
    message.data[1] = 0x0B;
    message.data[2] = 0x0C;
    message.data[3] = 0x0D;
    message.data[4] = 0x0E;
    message.data[5] = 0x0F;
    message.data[6] = 0x10;
    message.data[7] = 0x11;
    message.extd = 0;                // Standard 11-bit identifier
    message.rtr = 0;                 // Data frame (not a remote frame)
    message.ss = 1;                  // Not single shot
    message.self = 0;                // Normal transmission (not self reception)
    twai_send(&message);
    TextArea1Can_insertText[0] = '\0';
    snprintf(TextArea1Can_insertText, sizeof(TextArea1Can_insertText), "Message sent: %s ID=0x%03lX, Data=[%02X %02X %02X %02X %02X %02X %02X %02X]\r\n",
                    message.extd ? "Extended" : "Standard",
                    message.identifier,
                    message.data[0], message.data[1], message.data[2], message.data[3],
                    message.data[4], message.data[5], message.data[6], message.data[7]);
    lv_textarea_add_text(ui_TextArea1Can, TextArea1Can_insertText);
}

void Button_canTest2_clicked(lv_event_t * e)
{
    // ESP_LOGI(TAG,"Button_canTest2_clicked\n");
    twai_message_t message;
    message.identifier = 0x100;
    message.data_length_code = 8;
    message.data[0] = 0x01;
    message.data[1] = 0x02;
    message.data[2] = 0x03;
    message.data[3] = 0x04;
    message.data[4] = 0x05;
    message.data[5] = 0x06;
    message.data[6] = 0x07;
    message.data[7] = 0x08;
    message.extd = 1;                // Standard 11-bit identifier
    message.rtr = 0;                 // Data frame (not a remote frame)
    message.ss = 1;                  // Not single shot
    message.self = 0;                // Normal transmission (not self reception)
    twai_send(&message);
    TextArea1Can_insertText[0] = '\0';
    snprintf(TextArea1Can_insertText, sizeof(TextArea1Can_insertText), "Message sent: %s ID=0x%03lX, Data=[%02X %02X %02X %02X %02X %02X %02X %02X]\r\n",
                    message.extd ? "Extended" : "Standard",
                    message.identifier,
                    message.data[0], message.data[1], message.data[2], message.data[3],
                    message.data[4], message.data[5], message.data[6], message.data[7]);
    lv_textarea_add_text(ui_TextArea1Can, TextArea1Can_insertText);
}

void Button_canTest3_clicked(lv_event_t * e)
{
    // ESP_LOGI(TAG,"Button_canTest3_clicked\n");
    twai_message_t message;
    message.identifier = 0x050;
    message.data_length_code = 8;
    message.data[0] = 0x1a;
    message.data[1] = 0x2b;
    message.data[2] = 0x3c;
    message.data[3] = 0x4d;
    message.data[4] = 0x5e;
    message.data[5] = 0x6f;
    message.data[6] = 0x70;
    message.data[7] = 0x81;
    message.extd = 0;                // Standard 11-bit identifier
    message.rtr = 0;                 // Data frame (not a remote frame)
    message.ss = 1;                  // Not single shot
    message.self = 0;                // Normal transmission (not self reception)
    twai_send(&message);
    TextArea1Can_insertText[0] = '\0';
    snprintf(TextArea1Can_insertText, sizeof(TextArea1Can_insertText), "Message sent: %s ID=0x%03lX, Data=[%02X %02X %02X %02X %02X %02X %02X %02X]\r\n",
                    message.extd ? "Extended" : "Standard",
                    message.identifier,
                    message.data[0], message.data[1], message.data[2], message.data[3],
                    message.data[4], message.data[5], message.data[6], message.data[7]);
    lv_textarea_add_text(ui_TextArea1Can, TextArea1Can_insertText);
}

void button_CanClassClear_clicked(lv_event_t * e)
{
    lv_textarea_set_text(ui_TextArea1Can, "");
}
//********* page:canClass end ********* 

//********* page:imgView *********
const lv_image_dsc_t * imgView_image_list[] = {
    &ui_img_152448348,
    &ui_img_flower_b_800x480_png,
    &ui_img_flower_r_800x480_png,
    &ui_img_img_800x480_png,
};
static int imgView_image_index = 0;
void button_ImgViewLeft_clicked(lv_event_t * e)
{
    int indexMax = sizeof(imgView_image_list)/sizeof(lv_image_dsc_t*);

    if(imgView_image_index == 0)
    {
        imgView_image_index = indexMax - 1;
    }
    else
    {
        imgView_image_index--;
    }

    lv_image_set_src(ui_Image1, imgView_image_list[imgView_image_index]);
}

void button_ImgViewRight_clicked(lv_event_t * e)
{
    int indexMax = sizeof(imgView_image_list)/sizeof(lv_image_dsc_t*);

    imgView_image_index=(imgView_image_index+1)%indexMax;

    lv_image_set_src(ui_Image1, imgView_image_list[imgView_image_index]);
}
//********* page:imgView end *********
