// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: demo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Button_Backlight_clicked(lv_event_t * e);
void switch_IO__value_changed(lv_event_t * e);
void button_backlightOnOff_clicked(lv_event_t * e);
void slider_backlight_value_changed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
